# Generated by Django 2.2.5 on 2019-09-17 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.TextField(blank=True, max_length=50)),
                ('email', models.TextField(blank=True, max_length=50)),
                ('phone_number', models.IntegerField(blank=True, max_length=11)),
                ('ssc_roll', models.IntegerField(blank=True, max_length=6)),
                ('ssc_reg', models.IntegerField(blank=True, max_length=10)),
                ('ssc_board', models.CharField(choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('comilla', 'Comilla'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('sylhet', 'Sylhet'), ('dinajpur', 'Dinajpur'), ('jessore', 'Jessore')], default='এস.এস.সি বোর্ড বাছাই করুন', max_length=20)),
                ('verify', models.TextField(blank=True, max_length=10)),
                ('otp', models.TextField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
