# Generated by Django 2.2.5 on 2019-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='ssc_board',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='ssc_roll',
            field=models.IntegerField(blank=True, max_length=6, verbose_name='Enter your Roll: '),
        ),
    ]
