# Generated by Django 2.2.5 on 2019-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0003_auto_20190922_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='ssc_roll',
            field=models.IntegerField(blank=True, max_length=6),
        ),
    ]
