# Generated by Django 2.2.5 on 2019-10-01 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Khujun', '0005_auto_20190930_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone_number', models.IntegerField(blank=True, max_length=11)),
                ('ssc_roll', models.IntegerField(blank=True, max_length=6)),
                ('ssc_reg', models.IntegerField(blank=True, max_length=10)),
                ('ssc_board', models.CharField(blank=True, max_length=20)),
                ('verify', models.TextField(blank=True, max_length=10)),
                ('otp', models.TextField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
