# Generated by Django 2.2.5 on 2019-10-02 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0006_teacherregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Khujun.Album'),
        ),
    ]
