# Generated by Django 2.2.5 on 2019-10-02 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Khujun', '0007_auto_20191002_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherregistration',
            name='email',
        ),
        migrations.CreateModel(
            name='GuardianRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.IntegerField(blank=True, max_length=11)),
                ('nid', models.IntegerField(blank=True, max_length=14)),
                ('verify', models.TextField(blank=True, max_length=10)),
                ('otp', models.TextField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
