# Generated by Django 2.2.4 on 2019-10-03 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Khujun', '0009_auto_20191002_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.TextField(blank=True, max_length=50)),
                ('gender_name', models.CharField(blank=True, max_length=200)),
                ('blood_group', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True, max_length=50)),
                ('city', models.TextField(blank=True, max_length=50)),
                ('nid', models.TextField(blank=True, max_length=17)),
                ('school', models.TextField(blank=True, max_length=50)),
                ('college', models.TextField(blank=True, max_length=50)),
                ('university', models.TextField(blank=True, max_length=50)),
                ('subject', models.TextField(blank=True, max_length=50)),
                ('experience', models.TextField(blank=True, max_length=1000)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
