# Generated by Django 2.2.6 on 2019-10-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0013_teacherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='images',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
