# Generated by Django 2.2.4 on 2019-10-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0014_teacherprofile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='images',
        ),
        migrations.AlterField(
            model_name='teacherimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
