# Generated by Django 2.2.4 on 2019-10-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0016_teacherprofile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
