# Generated by Django 2.2.4 on 2019-10-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0018_auto_20191006_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherImage',
        ),
    ]
