# Generated by Django 2.2.6 on 2019-10-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0020_guardianprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianprofile',
            old_name='gender_name',
            new_name='gender_group',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='gender_name',
            new_name='gender_group',
        ),
    ]
