# Generated by Django 2.2.6 on 2019-10-07 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Khujun', '0022_auto_20191007_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_username', models.CharField(blank=True, max_length=50)),
                ('classes', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('day', models.CharField(blank=True, max_length=200)),
                ('payment', models.TextField(blank=True, max_length=50)),
                ('institute_name', models.TextField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, max_length=17)),
                ('teacher_confirm', models.TextField(blank=True, max_length=17)),
                ('guardian_confirm', models.TextField(blank=True, max_length=17)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
