# Generated by Django 2.2.6 on 2019-10-08 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Khujun', '0024_auto_20191008_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitioninfo',
            name='guardian_username',
        ),
        migrations.AddField(
            model_name='tuitioninfo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
