# Generated by Django 2.2.6 on 2019-10-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Khujun', '0025_auto_20191008_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitioninfo',
            name='user',
        ),
        migrations.AddField(
            model_name='tuitioninfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
