# Generated by Django 2.2.6 on 2019-10-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0026_auto_20191008_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='notification',
            field=models.IntegerField(default=0),
        ),
    ]
