# Generated by Django 2.2.6 on 2019-10-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0029_auto_20191011_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitioninfo',
            name='teacher_firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tuitioninfo',
            name='teacher_lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
