# Generated by Django 2.2.6 on 2019-10-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khujun', '0030_auto_20191012_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
